import 'package:flutter/material.dart';
import '../../core/constants/app_colors.dart';
import '../../core/widgets/premium_widgets.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? AppColors.backgroundDark : AppColors.background,
      appBar: const PremiumAppBar(title: "Terms of Service"),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSection(
              isDark,
              "1. Acceptance of Terms",
              "By accessing or using Nova AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the application.",
            ),
            _buildSection(
              isDark,
              "2. Use of Service",
              "Nova AI provides an AI-powered assistant. You agree to use the service only for lawful purposes. You are responsible for all content generated or shared through your use of the app.",
            ),
            _buildSection(
              isDark,
              "3. AI Disclaimer",
              "The content provided by Nova AI is generated by artificial intelligence. While we strive for accuracy, we cannot guarantee the correctness, completeness, or reliability of any AI-generated output. Use the information at your own risk.",
            ),
            _buildSection(
              isDark,
              "4. User Content",
              "You retain ownership of the prompts you provide. However, by using the service, you acknowledge that these prompts are processed by third-party AI models to provide responses.",
            ),
            _buildSection(
              isDark,
              "5. Prohibited Conduct",
              "You agree not to use Nova AI to generate harmful, illegal, offensive, or discriminatory content. We reserve the right to terminate access for users who violate these terms.",
            ),
            _buildSection(
              isDark,
              "6. Limitation of Liability",
              "Nova AI and its developers shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.",
            ),
            _buildSection(
              isDark,
              "7. Changes to Terms",
              "We reserve the right to modify these terms at any time. Your continued use of the app after changes are made signifies your acceptance of the new terms.",
            ),
            const SizedBox(height: 20),
            Center(
              child: Text(
                "Last Updated: October 2024",
                style: TextStyle(
                  fontSize: 12,
                  fontFamily: 'Poppins',
                  fontWeight: FontWeight.w600,
                  color: (isDark ? AppColors.textSecondaryDark : AppColors.textSecondary).withValues(alpha: 0.5),
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(bool isDark, String title, String content) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(left: 4, bottom: 12),
          child: Text(
            title,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.w800,
              fontFamily: 'Poppins',
              color: isDark ? AppColors.textPrimaryDark : AppColors.textPrimary,
              letterSpacing: -0.5,
            ),
          ),
        ),
        PremiumCard(
          padding: const EdgeInsets.all(20),
          child: Text(
            content,
            style: TextStyle(
              fontSize: 14,
              fontFamily: 'Poppins',
              height: 1.6,
              fontWeight: FontWeight.w500,
              color: isDark ? AppColors.textSecondaryDark : AppColors.textSecondary,
            ),
          ),
        ),
        const SizedBox(height: 28),
      ],
    );
  }
}
